spring:
  application:
    name: order-event-service
  kafka:
    consumer:
      bootstrap-servers: DESKTOP-7JUA3TN:9092
      group-id: orderGroup2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    mongodb:
      database: order-event-service
      host: localhost
      port: 27017


server:
  port: 8002


#eureka:
#  client:
#    service-url: http://localhost:8761/eureka
